### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [seger365/prj-rev-bwfs-dasmoto#3]
Alternatively, you can specify shared properties for multiple elements by including all the selectors separated by commas:

```css
h1, h2, .price {
  font-weight: bold;
}
```
